### PR TITLE
Refactor to make python3 compatible

### PR DESCRIPTION
**Pull request by steveryb**
There was a little bit of work to get this to work for python2 and python3, so this does that.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/198547794377466/224395852804586)

### CODE REVIEW

**Comment by periodic** [comment]
➤ Steven Rybicki commented:
https://app.asana.com/0/119586712338063/119586712338063, I can't see a way to add you as a reviewer/assignee for this or https://app.asana.com/0/198547794377466/224395153601260. I'm assigning them to you for now.

**Review by periodic — APPROVED** [review]

**Comment by steveryb** [comment]
@periodic, would you mind merging this and https://github.com/Asana/asana2sql/pull/4? I don't have write access here, so I can't :(

**Comment by periodic** [comment]
➤ Drew Haven commented:
Oh! We should fix that.  I'll take care of it for now though.

**Comment by periodic** [comment]
➤ Drew Haven commented:
Wow, actually, I appear to have lost write access to all my repositories too...

**Comment by periodic** [comment]
➤ Drew Haven commented:
Done, finally.

**Pull request merged**
